# Naive Bayes 

Our questions

Classification algorithm - spam filter

In [1]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

import requests
import urllib
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn import datasets, tree, metrics, svm

import statsmodels.api as sm
from statsmodels.nonparametric.kde import KDEUnivariate
#from statsmodels.nonparametric import smoothers_lowes

import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('recipes.csv')

In [3]:
df.head()

cuisine     id                                    ingredient_list
0        greek  10259  romaine lettuce, black olives, grape tomatoes,...
1  southern_us  25693  plain flour, ground pepper, salt, tomatoes, gr...
2     filipino  20130  eggs, pepper, salt, mayonaise, cooking oil, gr...
3       indian  22213                  water, vegetable oil, wheat, salt
4       indian  13162  black pepper, shallots, cornflour, cayenne pep...

# Classify the various Recipes

Looking for Italian Food.

FOR CLASSIFYING algorithms you must have categories on your original data set.

**Clustering**
1. Docs
2. Feed it to algorithm. Tell it to create X number of categories
3. The machine gives you back the categories

**For classification**
1. Docs
2. Classify the ones you want
3. Ask algorithm which categories a new bunch of unlabeled documents end up in

## Naive Bayes is just a probability test

You have to convert it into numbers

- if you see a word is normally in spam email, there's chance it's spam
- if you see a word in normally in non-spam e

# Converting text into numbers 
1. Labels
2. Features

In [4]:
#Converting our labels into numbers
#italian = 1
#not italian = 0

In [5]:
def make_label(cuisine):
    if cuisine == "italian":
        return 1
    else:
        return 0

In [6]:
df['label'] = df['cuisine'].apply(make_label)
df.head(10)

cuisine     id                                    ingredient_list  \
0        greek  10259  romaine lettuce, black olives, grape tomatoes,...   
1  southern_us  25693  plain flour, ground pepper, salt, tomatoes, gr...   
2     filipino  20130  eggs, pepper, salt, mayonaise, cooking oil, gr...   
3       indian  22213                  water, vegetable oil, wheat, salt   
4       indian  13162  black pepper, shallots, cornflour, cayenne pep...   
5     jamaican   6602  plain flour, sugar, butter, eggs, fresh ginger...   
6      spanish  42779  olive oil, salt, medium shrimp, pepper, garlic...   
7      italian   3735  sugar, pistachio nuts, white almond bark, flou...   
8      mexican  16903  olive oil, purple onion, fresh pineapple, pork...   
9      italian  12734  chopped tomatoes, fresh basil, garlic, extra-v...   

   label  
0      0  
1      0  
2      0  
3      0  
4      0  
5      0  
6      0  
7      1  
8      0  
9      1

## Converting our features into numbers

**Features selection** What ingredients we want to look at

Whether it has spaghetti or not. 

In [7]:
df['has_spaghetti'] = df['ingredient_list'].str.contains('spaghetti')
df['has_curry_powder'] = df['ingredient_list'].str.contains('curry powder')
df.head(10)

cuisine     id                                    ingredient_list  \
0        greek  10259  romaine lettuce, black olives, grape tomatoes,...   
1  southern_us  25693  plain flour, ground pepper, salt, tomatoes, gr...   
2     filipino  20130  eggs, pepper, salt, mayonaise, cooking oil, gr...   
3       indian  22213                  water, vegetable oil, wheat, salt   
4       indian  13162  black pepper, shallots, cornflour, cayenne pep...   
5     jamaican   6602  plain flour, sugar, butter, eggs, fresh ginger...   
6      spanish  42779  olive oil, salt, medium shrimp, pepper, garlic...   
7      italian   3735  sugar, pistachio nuts, white almond bark, flou...   
8      mexican  16903  olive oil, purple onion, fresh pineapple, pork...   
9      italian  12734  chopped tomatoes, fresh basil, garlic, extra-v...   

   label has_spaghetti has_curry_powder  
0      0         False            False  
1      0         False            False  
2      0         False            False  
3      0         False            False  
4      0         False            False  
5      0         False            False  
6      0         False            False  
7      1         False            False  
8      0         False            False  
9      1         False            False

In [8]:
# Three Naive Bayes:
# Gossian (not much)

# If Text is long: 
# Multinominal Naive Bayes (uses a lot of text). You count the words.

# True False, which is better for long passages.
# Bernoulli Naive Bayes. YOu only care if the word shows up, or if it doesn't.

# Taking columns out

In [9]:
df[['has_spaghetti', 'has_curry_powder']].head()

has_spaghetti has_curry_powder
0         False            False
1         False            False
2         False            False
3         False            False
4         False            False

In [10]:
from sklearn.cross_validation import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    df[['has_spaghetti', 'has_curry_powder']], 
    df['label'], 
    test_size=.2)

In [12]:
len(X_train)

31819

In [13]:
len(X_test)

7955

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    df[['has_spaghetti', 'has_curry_powder']], 
    df['label'], 
    test_size=.2)

In [15]:
from sklearn import naive_bayes

In [16]:
#Create Bernoulli classifier
clf = naive_bayes.BernoulliNB()
#Feed classifier two things.
clf.fit(X_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [17]:
#This looks ugly but in theory it's what every recipe.
#We know first three and last three aren't Italian
clf.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])

In [18]:
clf.score(X_train, y_train)

0.81149627581005057

In [19]:
clf.score(X_test, y_test)

0.80641106222501568

In [20]:
def make_label_indian(cuisine):
    if cuisine == "indian":
        return 1
    else:
        return 0

In [21]:
df['is_indian'] = df['cuisine'].apply(make_label_indian)

In [22]:
df.head()

cuisine     id                                    ingredient_list  \
0        greek  10259  romaine lettuce, black olives, grape tomatoes,...   
1  southern_us  25693  plain flour, ground pepper, salt, tomatoes, gr...   
2     filipino  20130  eggs, pepper, salt, mayonaise, cooking oil, gr...   
3       indian  22213                  water, vegetable oil, wheat, salt   
4       indian  13162  black pepper, shallots, cornflour, cayenne pep...   

   label has_spaghetti has_curry_powder  is_indian  
0      0         False            False          0  
1      0         False            False          0  
2      0         False            False          0  
3      0         False            False          1  
4      0         False            False          1

In [46]:
df['has_turmeric'] = df['ingredient_list'].str.contains('turmeric')
df['has_cardamom'] = df['ingredient_list'].str.contains('cardamom')
df['has_cheese'] = df['ingredient_list'].str.contains('cheese')
df.head(10)

cuisine     id                                    ingredient_list  \
0        greek  10259  romaine lettuce, black olives, grape tomatoes,...   
1  southern_us  25693  plain flour, ground pepper, salt, tomatoes, gr...   
2     filipino  20130  eggs, pepper, salt, mayonaise, cooking oil, gr...   
3       indian  22213                  water, vegetable oil, wheat, salt   
4       indian  13162  black pepper, shallots, cornflour, cayenne pep...   
5     jamaican   6602  plain flour, sugar, butter, eggs, fresh ginger...   
6      spanish  42779  olive oil, salt, medium shrimp, pepper, garlic...   
7      italian   3735  sugar, pistachio nuts, white almond bark, flou...   
8      mexican  16903  olive oil, purple onion, fresh pineapple, pork...   
9      italian  12734  chopped tomatoes, fresh basil, garlic, extra-v...   

   label has_spaghetti has_curry_powder  is_indian has_turmeric has_cardamom  \
0      0         False            False          0        False        False   
1      0         False            False          0        False        False   
2      0         False            False          0        False        False   
3      0         False            False          1        False        False   
4      0         False            False          1        False        False   
5      0         False            False          0        False        False   
6      0         False            False          0        False        False   
7      1         False            False          0        False        False   
8      0         False            False          0        False        False   
9      1         False            False          0        False        False   

  has_cheese  
0       True  
1      False  
2      False  
3      False  
4      False  
5      False  
6      False  
7      False  
8       True  
9      False

In [63]:
X_train, X_test, y_train, y_test = train_test_split(
    df[['has_turmeric', 'has_cheese']], 
    df['cuisine_label'], 
    test_size=.2)

In [64]:
#Create Bernoulli classifier
clf = naive_bayes.BernoulliNB()
#Feed classifier two things.
clf.fit(X_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [65]:
clf.score(X_train, y_train)

0.22241428077563719

In [66]:
clf.score(X_test, y_test)

0.21785040854808296

# Let's fix up our labels

In [ ]:
#LabelEncoder to rescue

In [55]:
from sklearn import preprocessing

In [56]:
le = preprocessing.LabelEncoder()

In [57]:
le.fit(['orange', 'red', 'yellow', 'blue'])

LabelEncoder()

In [58]:
le.transform(['orange', 'red', 'yellow', 'blue'])

array([1, 2, 3, 0])

In [59]:
#send the label encoder each and every cuisine
le.fit(df['cuisine'])

LabelEncoder()

In [60]:
le.transform(df['cuisine'])

array([ 6, 16,  4, ...,  8,  3, 13])

In [62]:
df['cuisine_label'] = le.transform(df['cuisine'])
df.head(3)

cuisine     id                                    ingredient_list  \
0        greek  10259  romaine lettuce, black olives, grape tomatoes,...   
1  southern_us  25693  plain flour, ground pepper, salt, tomatoes, gr...   
2     filipino  20130  eggs, pepper, salt, mayonaise, cooking oil, gr...   

   label has_spaghetti has_curry_powder  is_indian has_turmeric has_cardamom  \
0      0         False            False          0        False        False   
1      0         False            False          0        False        False   
2      0         False            False          0        False        False   

  has_cheese  cuisine_label  
0       True              6  
1      False             16  
2      False              4

In [73]:
X_train, X_test, y_train, y_test = train_test_split(
    df[['has_turmeric', 'has_cheese', 'has_spaghetti', 'has_cardamom', 'has_curry_powder']], 
    df['cuisine_label'], 
    test_size=.2)

In [74]:
#Create Bernoulli classifier
clf = naive_bayes.BernoulliNB()
#Feed classifier two things.
clf.fit(X_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [75]:
clf.score(X_train, y_train)

0.24639366416292152

In [76]:
clf.score(X_test, y_test)

0.23557510999371464

# Automatic way to pick out all of the words

In [77]:
from sklearn.feature_extraction.text import CountVectorizer

In [102]:
#vectorizer = CountVectorizer()
#Most popular quotes, and olive oil
vectorizer = CountVectorizer(ngram_range=(1,2), max_features=3000)

In [103]:
#http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

In [104]:
#Sentences, which the vectorizor will learn:
sentences = [
    'cats are cool',
    'dogs are cool'
]
vectorizer.fit(sentences)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=3000, min_df=1,
        ngram_range=(1, 2), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [105]:
#Converting it into numbers

In [106]:
vectorizer.transform(sentences)

<2x7 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [107]:
vectorizer.transform(sentences).toarray()

array([[1, 1, 1, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 1, 1]])

In [108]:
#learn all of these words
vectorizer.fit(df['ingredient_list'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=3000, min_df=1,
        ngram_range=(1, 2), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [109]:
#please convert ingredient_list into features
every_single_word_features = vectorizer.transform(df['ingredient_list'])

In [110]:
#Now with nre complete labels and features

In [111]:
predictions = clf.predict(sentences_words_features)
predictions

In [112]:
#Create Bernoulli classifier, NAive BAys
clf = naive_bayes.BernoulliNB()
#Feed classifier two things.
%time clf.fit(X_train, y_train)
print(clf.score(X_train, y_train))
print(clf.score(X_test, y_test))

CPU times: user 39.4 ms, sys: 12.2 ms, total: 51.6 ms
Wall time: 51.7 ms
0.715075898048
0.681835323696


In [113]:
#Decision tree classifier
from sklearn import tree
tree_clf = tree.DecisionTreeClassifier()
%time  tree_clf.fit(X_train, y_train)
print(tree_clf.score(X_train, y_train))
print(tree_clf.score(X_test, y_test))

CPU times: user 12.2 s, sys: 46.6 ms, total: 12.2 s
Wall time: 12.3 s
0.999780005657
0.643117536141


In [114]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

forest_clf = RandomForestClassifier()
%time  forest_clf.fit(X_train, y_train)
print(forest_clf.score(X_train, y_train))
print(forest_clf.score(X_test, y_test))

CPU times: user 7.36 s, sys: 69 ms, total: 7.43 s
Wall time: 7.46 s
0.992017348125
0.707102451288


In [115]:
#How do you do this in the real world with new data?

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    every_single_word_features, 
    df['cuisine_label'], 
    test_size=.2)


In [116]:
clf = naive_bayes.BernoulliNB()
#Feed classifier two things.
%time clf.fit(every_single_word_features, df['cuisine_label'])
new_data_we_dont_know_about = X_train
print(clf.score(X_train, y_train))
print(clf.score(X_test, y_test))

CPU times: user 38.1 ms, sys: 18 ms, total: 56.1 ms
Wall time: 55.3 ms
0.715075898048
0.681835323696


In [ ]:
every_single_word_features = vectorizer.transform(df['ingredient_list'])